### ISSUE TITLE
Update the PyPI release to 1.0.2 and upload the readme

### ISSUE THREAD

**Issue by wolph** [bbelyeu/Flask-SQLAlchemy-Caching#4]
The current PyPI page is completely empty which is a shame since this repo has a nice README :)

https://pypi.org/project/Flask-SQLAlchemy-Caching/

Also, the version is 1 minor version out of date but that seems to be documentation only.

**Comment by bbelyeu** [comment]
This is true. I'm just bogged down with other projects at the moment. I'll try to get to this soon.
